sonar.organization=cheshire-12

# Уникальный ключ проекта
sonar.projectKey=Cheshire-12_python-project-52
sonar.projectName=Task Manager

sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=.
sonar.language=py
sonar.python.version=3.14
sonar.exclusions=**/migrations/**, .venv/**, staticfiles/**, manage.py
sonar.tests=task_manager/tests
sonar.test.inclusions=**/tests/**, **/test_*.py