# Generated by Django 6.0.7 on 2026-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_llabels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='llabels',
            new_name='labels',
        ),
    ]
